/**
 * EtherNet/IP Source Helpers
 *
 * Provides type-safe helpers for sourcing PLC variables from EtherNet/IP devices.
 * Use with generated device types from `codegen.ts` for compile-time tag validation.
 *
 * @example
 * ```typescript
 * import { eipAll } from "@tentacle/plc";
 * import { rtu45, udtTemplates } from "./generated/ethernetip.ts";
 *
 * // All tags at once (preserves key autocomplete):
 * const variables = { ...eipAll(rtu45, udtTemplates) };
 *
 * // Filtered (loses key autocomplete since keys depend on runtime regex):
 * const variables = { ...eipAll(rtu45, udtTemplates, { match: /^RTU45_RECLM/ }) };
 *
 * // Single tag with overrides:
 * import { eipVar } from "@tentacle/plc";
 * const temp = eipVar(rtu45, "RTU45_RECLM_PIT_001.VALUE", {
 *   description: "Pit temperature",
 *   deadband: { value: 0.1 },
 * });
 *
 * // Filter-based RBE with individual overrides:
 * const variables = { ...eipAll(rtu45, udtTemplates, {
 *   deadband: { value: 1.0 },                    // default for all numerics
 *   rbeRules: [
 *     { match: /PIT_\d+\.VALUE/, deadband: { value: 0.1, maxTime: 30000 } },
 *     { match: /TIT_\d+\.VALUE/, deadband: { value: 0.5, maxTime: 60000 } },
 *     { match: /STATUS/,         disableRBE: true },
 *   ],
 *   rbeOverrides: {
 *     "RTU45_RECLM_PIT_001.VALUE": { deadband: { value: 0.01 } },
 *   },
 * }) };
 * ```
 */

import {
  resolveRbe,
  type DeadBandConfig,
  type PlcVariableBooleanConfig,
  type PlcVariableConfig,
  type PlcVariableNumberConfig,
  type PlcVariableStringConfig,
  type PlcVariableUdtConfig,
  type RbeOverride,
  type RbeRule,
  type UdtTemplateDefinition,
  type VariableSource,
} from "./types/variables.ts";

/** Shape of a generated EIP device constant (from codegen) */
export type EipDevice = {
  readonly id: string;
  readonly host: string;
  readonly port: number;
  readonly scanRate?: number;
  readonly tags: Readonly<Record<string, { readonly datatype: string; readonly cipType?: string }>>;
  readonly structTags?: Readonly<Record<string, string>>;
};

/** Map of UDT type names to their template definitions (generated by codegen) */
export type UdtTemplateMap = Readonly<Record<string, UdtTemplateDefinition>>;

/** Source descriptor for an EtherNet/IP tag */
export type EthernetIPSource = {
  deviceId: string;
  host: string;
  port: number;
  tag: string;
  cipType?: string;
};

/** Optional overrides for eipVar / eipUdtVar */
type EipVarOptions = {
  id?: string;
  description?: string;
  deadband?: DeadBandConfig;
  disableRBE?: boolean;
};

/** Extract the UDT type name values from a device's structTags */
type UdtTypeNames<D extends EipDevice> = D extends { readonly structTags: Readonly<Record<string, infer V>> }
  ? V & string
  : string;

/** Filter options for bulk functions */
type EipBulkOptions<D extends EipDevice = EipDevice> = {
  /** Only include tags whose name matches this pattern */
  match?: RegExp;
  /** Exclude tags whose name matches this pattern */
  exclude?: RegExp;
  /** Only include struct tags whose UDT type name is in this list (also includes their atomic member tags) */
  structTypes?: UdtTypeNames<D>[];
  /** When using structTypes, also include all standalone atomic tags (tags not part of any struct) */
  includeAtomicTags?: boolean;
  /** Scan rate in ms for EtherNet/IP polling (default: 1000) */
  scanRate?: number;
  /** Default RBE deadband applied to all numeric variables (lowest priority) */
  deadband?: DeadBandConfig;
  /** Disable RBE checking on all variables (lowest priority) */
  disableRBE?: boolean;
  /** Pattern-based RBE rules — first matching rule wins (overrides default deadband/disableRBE) */
  rbeRules?: RbeRule[];
  /** Per-tag RBE overrides — highest priority */
  rbeOverrides?: Record<string, RbeOverride>;
};

/** Extract structTags keys if present, else never */
type StructTagKeys<D extends EipDevice> = D extends { readonly structTags: Readonly<Record<infer K, string>> }
  ? K & string
  : never;

/** All tag keys across tags + structTags */
type AllTagKeys<D extends EipDevice> = (keyof D["tags"] & string) | StructTagKeys<D>;

/**
 * Create a type-safe EtherNet/IP source for a PLC variable.
 */
export function eipTag<D extends EipDevice>(
  device: D,
  tag: keyof D["tags"] & string,
): { ethernetip: EthernetIPSource } {
  const cipType = device.tags[tag]?.cipType;
  return {
    ethernetip: {
      deviceId: device.id,
      host: device.host,
      port: device.port,
      tag,
      ...(cipType ? { cipType } : {}),
    },
  };
}

/**
 * Infer the PLC variable datatype from a device tag's datatype string.
 */
function inferDatatype(
  raw: string,
): "number" | "boolean" | "string" {
  switch (raw) {
    case "BOOL":
    case "boolean":
      return "boolean";
    case "STRING":
    case "string":
      return "string";
    default:
      return "number";
  }
}

/** Build an EthernetIPSource object */
function makeSource(device: EipDevice, tag: string, cipType?: string, scanRate?: number): { ethernetip: EthernetIPSource } {
  const rate = scanRate ?? device.scanRate;
  return {
    ethernetip: {
      deviceId: device.id,
      host: device.host,
      port: device.port,
      tag,
      ...(cipType ? { cipType } : {}),
      ...(rate ? { scanRate: rate } : {}),
    },
  };
}

/** Create an atomic variable config from a tag name and datatype string */
function makeAtomicVar(
  device: EipDevice,
  tagName: string,
  raw: string,
  cipType?: string,
  bulkOptions?: EipBulkOptions,
): PlcVariableNumberConfig | PlcVariableBooleanConfig | PlcVariableStringConfig {
  const dt = inferDatatype(raw);
  const id = tagName.replace(/[^a-zA-Z0-9_]/g, "_");
  const rbe = resolveRbe(tagName, bulkOptions);
  const base = {
    id,
    description: "",
    source: makeSource(device, tagName, cipType, bulkOptions?.scanRate),
    ...(rbe.disableRBE ? { disableRBE: true } : {}),
  };
  switch (dt) {
    case "boolean":
      return { ...base, datatype: "boolean", default: false };
    case "string":
      return { ...base, datatype: "string", default: "" };
    default:
      return { ...base, datatype: "number", default: 0, ...(rbe.deadband ? { deadband: rbe.deadband } : {}) };
  }
}

/** Build a default value object from a UDT template, resolving nested templateRefs */
function buildUdtDefault(template: UdtTemplateDefinition, templates?: UdtTemplateMap): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const member of template.members) {
    // Skip array members — libplctag can't read them as individual tags
    if ("isArray" in member && member.isArray) continue;
    if (member.templateRef && templates) {
      const nested = templates[member.templateRef];
      if (nested) {
        result[member.name] = buildUdtDefault(nested, templates);
        continue;
      }
    }
    switch (member.datatype) {
      case "boolean":
        result[member.name] = false;
        break;
      case "string":
        result[member.name] = "";
        break;
      default:
        result[member.name] = 0;
        break;
    }
  }
  return result;
}

/** Build per-member EIP sources for a UDT, resolving nested templateRefs into dotted paths */
function buildMemberSources(
  device: EipDevice,
  tagName: string,
  template: UdtTemplateDefinition,
  templates?: UdtTemplateMap,
  scanRate?: number,
): Record<string, VariableSource> {
  const sources: Record<string, VariableSource> = {};
  const rate = scanRate ?? device.scanRate;
  for (const member of template.members) {
    // Skip array members — libplctag can't read them as individual tags
    if ("isArray" in member && member.isArray) continue;
    const memberTag = `${tagName}.${member.name}`;
    if (member.templateRef && templates) {
      const nested = templates[member.templateRef];
      if (nested) {
        // Recurse into nested UDT — prefix member paths with parent member name
        const nestedSources = buildMemberSources(device, memberTag, nested, templates, scanRate);
        for (const [nestedPath, source] of Object.entries(nestedSources)) {
          sources[`${member.name}.${nestedPath}`] = source;
        }
        continue;
      }
    }
    // Atomic member — look up cipType from device tags
    const cipType = device.tags[memberTag]?.cipType;
    sources[member.name] = {
      ethernetip: {
        deviceId: device.id ?? "unknown",
        host: device.host,
        port: device.port ?? 44818,
        tag: memberTag,
        cipType,
        ...(rate ? { scanRate: rate } : {}),
      },
    };
  }
  return sources;
}

/** Create a UDT variable config with per-member EIP sources.
 *  libplctag can't read whole structs, so each member gets its own source.
 *  The PLC runtime assembles UDT values from individual member updates. */
function makeUdtVar(
  device: EipDevice,
  tagName: string,
  template: UdtTemplateDefinition,
  templates?: UdtTemplateMap,
  bulkOptions?: EipBulkOptions,
): PlcVariableUdtConfig {
  const id = tagName.replace(/[^a-zA-Z0-9_]/g, "_");
  const rbe = resolveRbe(tagName, bulkOptions);
  return {
    id,
    description: `${template.name} instance`,
    datatype: "udt",
    default: buildUdtDefault(template, templates),
    udtTemplate: template,
    memberSources: buildMemberSources(device, tagName, template, templates, bulkOptions?.scanRate),
    ...(rbe.deadband ? { deadband: rbe.deadband } : {}),
    ...(rbe.disableRBE ? { disableRBE: true } : {}),
  };
}

/**
 * Create a fully-wired PlcVariableConfig for a single atomic EtherNet/IP tag.
 *
 * Infers the datatype from the generated device constant so you don't have to
 * spell out `datatype`, `default`, or `source` by hand.
 */
export function eipVar<D extends EipDevice>(
  device: D,
  tag: keyof D["tags"] & string,
  options?: EipVarOptions,
): PlcVariableNumberConfig | PlcVariableBooleanConfig | PlcVariableStringConfig {
  const raw = device.tags[tag]?.datatype ?? "number";
  const dt = inferDatatype(raw);
  const id = options?.id ?? tag.replace(/[^a-zA-Z0-9_]/g, "_");
  const base = {
    id,
    description: options?.description ?? "",
    source: eipTag(device, tag),
    ...(options?.deadband ? { deadband: options.deadband } : {}),
    ...(options?.disableRBE ? { disableRBE: options.disableRBE } : {}),
  };
  switch (dt) {
    case "boolean":
      return { ...base, datatype: "boolean", default: false } as PlcVariableBooleanConfig;
    case "string":
      return { ...base, datatype: "string", default: "" } as PlcVariableStringConfig;
    default:
      return { ...base, datatype: "number", default: 0 } as PlcVariableNumberConfig;
  }
}

/**
 * Create a fully-wired PlcVariableUdtConfig for a single struct EtherNet/IP tag.
 *
 * UDT variables have no EIP source — libplctag can't read whole structs.
 * The PLC runtime assembles UDT values from individual member variable updates.
 */
export function eipUdtVar<D extends EipDevice>(
  _device: D,
  tag: StructTagKeys<D>,
  template: UdtTemplateDefinition,
  options?: EipVarOptions,
): PlcVariableUdtConfig {
  const tagStr = tag as string;
  const id = options?.id ?? tagStr.replace(/[^a-zA-Z0-9_]/g, "_");
  return {
    id,
    description: options?.description ?? `${template.name} instance`,
    datatype: "udt",
    default: buildUdtDefault(template),
    udtTemplate: template,
    ...(options?.deadband ? { deadband: options.deadband } : {}),
    ...(options?.disableRBE ? { disableRBE: options.disableRBE } : {}),
  };
}

// ─── Bulk functions ──────────────────────────────────────────────────────────

/** Check if a tag name passes match/exclude filters */
function passesFilter(tagName: string, options?: EipBulkOptions, structTagTypes?: Record<string, string>): boolean {
  if (options?.match && !options.match.test(tagName)) return false;
  if (options?.exclude && options.exclude.test(tagName)) return false;
  if (options?.structTypes && structTagTypes) {
    // Check if this tag is a struct tag with a matching type, or an atomic member of one
    const isMatchingStruct = structTagTypes[tagName] && options.structTypes.includes(structTagTypes[tagName]);
    const isMatchingMember = Object.entries(structTagTypes).some(
      ([structName, udtName]) => tagName.startsWith(structName + ".") && options.structTypes!.includes(udtName),
    );
    // Check if this is a standalone atomic tag (not a member of any struct)
    const isStandaloneAtomic = options.includeAtomicTags &&
      !structTagTypes[tagName] &&
      !Object.keys(structTagTypes).some((structName) => tagName.startsWith(structName + "."));
    if (!isMatchingStruct && !isMatchingMember && !isStandaloneAtomic) return false;
  }
  return true;
}

/**
 * Bulk-create PlcVariableConfigs for all atomic tags on a device.
 * Without a filter, preserves tag name keys for autocomplete.
 */
export function eipVars<D extends EipDevice>(
  device: D,
): { [K in keyof D["tags"] & string]: PlcVariableConfig };
export function eipVars<D extends EipDevice>(
  device: D,
  options: EipBulkOptions<D>,
): Record<string, PlcVariableConfig>;
export function eipVars(
  device: EipDevice,
  options?: EipBulkOptions,
): Record<string, PlcVariableConfig> {
  const result: Record<string, PlcVariableConfig> = {};
  for (const [tagName, tagInfo] of Object.entries(device.tags)) {
    if (!passesFilter(tagName, options, device.structTags as Record<string, string> | undefined)) continue;
    result[tagName] = makeAtomicVar(device, tagName, tagInfo.datatype, tagInfo.cipType, options);
  }
  return result;
}

/**
 * Bulk-create PlcVariableUdtConfigs for all struct tags on a device.
 * Without a filter, preserves struct tag name keys for autocomplete.
 */
export function eipUdtVars<D extends EipDevice>(
  device: D,
  templates: UdtTemplateMap,
): { [K in StructTagKeys<D>]: PlcVariableUdtConfig };
export function eipUdtVars<D extends EipDevice>(
  device: D,
  templates: UdtTemplateMap,
  options: EipBulkOptions<D>,
): Record<string, PlcVariableUdtConfig>;
export function eipUdtVars(
  device: EipDevice,
  templates: UdtTemplateMap,
  options?: EipBulkOptions,
): Record<string, PlcVariableUdtConfig> {
  const result: Record<string, PlcVariableUdtConfig> = {};
  if (!device.structTags) return result;
  for (const [tagName, udtName] of Object.entries(device.structTags)) {
    if (!passesFilter(tagName, options, device.structTags as Record<string, string>)) continue;
    const template = templates[udtName];
    if (!template) continue;
    result[tagName] = makeUdtVar(device, tagName, template, templates, options);
  }
  return result;
}

/**
 * Bulk-create PlcVariableConfigs for ALL tags on a device (atomic + struct).
 * Without a filter, preserves all tag name keys for autocomplete.
 */
export function eipAll<D extends EipDevice>(
  device: D,
  templates?: UdtTemplateMap,
): { [K in AllTagKeys<D>]: PlcVariableConfig };
export function eipAll<D extends EipDevice>(
  device: D,
  templates: UdtTemplateMap | undefined,
  options: EipBulkOptions<D>,
): Record<string, PlcVariableConfig>;
export function eipAll(
  device: EipDevice,
  templates?: UdtTemplateMap,
  options?: EipBulkOptions,
): Record<string, PlcVariableConfig> {
  const result: Record<string, PlcVariableConfig> = {};
  const structTagTypes = device.structTags as Record<string, string> | undefined;
  // Build UDT variables first — they carry memberSources for EIP subscriptions,
  // so their atomic member tags can be skipped from the result.
  const includedStructNames = new Set<string>();
  if (templates && device.structTags) {
    for (const [tagName, udtName] of Object.entries(device.structTags)) {
      if (!passesFilter(tagName, options, structTagTypes)) continue;
      const template = templates[udtName];
      if (!template) continue;
      includedStructNames.add(tagName);
      result[tagName] = makeUdtVar(device, tagName, template, templates, options);
    }
  }
  for (const [tagName, tagInfo] of Object.entries(device.tags)) {
    // Skip atomic members of included structs — their sources are in the UDT's memberSources
    if (includedStructNames.size > 0) {
      const dotIdx = tagName.indexOf(".");
      if (dotIdx !== -1 && includedStructNames.has(tagName.substring(0, dotIdx))) continue;
    }
    if (!passesFilter(tagName, options, structTagTypes)) continue;
    result[tagName] = makeAtomicVar(device, tagName, tagInfo.datatype, tagInfo.cipType, options);
  }
  return result;
}
